image: python:3.6-alpine
  
stages:
  - deploy

before_script:
   - pip install twine
   # "You should always upload a source archive and provide built archives..." - PyPi
   - python setup.py sdist bdist_wheel
   # Do we want to do what old internal documentation referenced?
   #- python setup.py bdist_wheel --universal

# Upload to Test PyPi
deploy_staging:
  stage: deploy
  variables:
    TWINE_USERNAME: $STAGING_USERNAME
    TWINE_PASSWORD: $STAGING_PASSWORD
  script:
    #- twine upload dist/*
    - twine upload --repository-url $STAGING_REPO_URL dist/*
  except:
    - tags

deploy_production:
  stage: deploy
  variables:
    TWINE_USERNAME: $PRODUCTION_USERNAME
    TWINE_PASSWORD: $PRODUCTION_PASSWORD
  script:
    - twine upload dist/*
  only:
    - tags
