Table of contents
=============================

* [[Home]]


* [[Integration process|Kount-Access-Integration]]

* [[Prerequisites|Kount-Access-Prerequisites]]

  * [[Required Data|Kount-Access-Prerequisites#required-information]]

  * [[Download and build|Kount-Access-Prerequisites#downloading-and-building-the-sdk]]

* [[Kount Access configuration|Kount-Access-Environments,-API-Keys,-and-Thresholds]]

  * [[Creating an API Key|Kount-Access-Environments,-API-Keys,-and-Thresholds#creating-an-api-key]]

  * [[Configuring thresholds|Kount-Access-Environments,-API-Keys,-and-Thresholds#threshold-configuration]]

* [[Technical Reference|Technical-Reference]]

  * [[Data Collector]]

  * [[Kount Access Endpoints]]

    * [[/device|Kount-Access-Endpoints#device-post-httpskount-access-hostdevice]]

    * [[/velocity|Kount-Access-Endpoints#velocity-post-httpskount-access-hostvelocity]]

    * [[/decision|Kount-Access-Endpoints#decision-post-httpskount-access-hostdecision]]

    * [[Sample Response in JSON|Kount-Access-Endpoints#sample-json-response-object]]

  * [[Kount Access Sample Code|Kount-Access-Examples]]

* [[Kount Access and Content Security Policy|Kount-Access-and-Content-Security-Policy]]

* [[Kount Access SW metrics|SW-metrics]]

