Technical Reference
======================================

*  `Data Collector <Data-Collector>`_

*  `Kount Access Endpoints <Kount-Access-Endpoints>`_
        
        * `/device <Kount-Access-Endpoints#device-post-httpskount-access-hostdevice>`_
        
        * `/velocity <Kount-Access-Endpoints#velocity-post-httpskount-access-hostvelocity>`_
        
        * `/decision <Kount-Access-Endpoints#decision-post-httpskount-access-hostdecision>`_

* `Kount Access Examples <Kount-Access-Examples>`_
