Technical Reference
======================================

*  `Data Collector <Data-Collector.html>`_

*  `Kount Access Endpoints <Kount-Access-Endpoints.html>`_
        
        * `/device <Kount-Access-Endpoints.html#id1>`_
        
        * `/velocity <Kount-Access-Endpoints.html#id2>`_
        
        * `/decision <Kount-Access-Endpoints.html#id3>`_

* `Kount Access Examples <Kount-Access-Examples.html>`_
